// Vite config for the bundle baseline measurement (RRU-100).
//
// WHY A SECOND CONFIG. RRU-092 measures ONE bundle — the selective import
// (`Button` + `ChevronDown`) — which answers "does importing a component drag the
// library in?". It cannot answer the other half of §29: how big is the library
// as a whole, and what does each component cost inside it. A consumer that uses
// a table, a dialog and a select needs those numbers, and there is no honest way
// to get them without building the thing: summing `dist/` files with gzip (the
// cheap approach) reports 18.7 kB of CSS where the real production asset is
// 5.46 kB, because the authored stylesheets carry the documentation comments
// that the minifier deletes.
//
// So this config builds two MORE entry points, both generated by
// `tools/measure-bundle.mjs` (never committed, so a new component cannot make
// the baseline silently stale):
//
//   full   every public export of `@raulrod/ui` + the public stylesheet. This is
//          the worst case ("import the library"), and it is where the per
//          component / per icon breakdown comes from: `rollup-plugin-visualizer`
//          reports the bytes each module contributed to the real bundle.
//   icons  every icon of the catalog through `@raulrod/icons`. It quantifies
//          what the `export *` of ADR-007 would cost a consumer who pulled the
//          whole set instead of the one icon they use — the number that makes
//          "you only pay per icon" a measurement instead of an intention.
//
// The entry is chosen with an env var instead of one config per entry: the two
// builds differ ONLY in input and outDir, and a third config file would be a
// third copy of everything else that could drift. `RRU_BASELINE_ENTRY` is read
// here rather than in a script because the entry name and its output folder have
// to travel together — that is what the measurement indexes.
/// <reference types="node" />
import { visualizer } from "rollup-plugin-visualizer";
import { defineConfig, mergeConfig } from "vite";

import baseConfig from "./vite.config.js";

const ENTRIES = {
  full: {
    input: ".bundle-baseline/full.tsx",
    outDir: "dist-bundle-baseline-full",
    title: "RRU-100 — Full public API of @raulrod/ui",
  },
  icons: {
    input: ".bundle-baseline/icons.tsx",
    outDir: "dist-bundle-baseline-icons",
    title: "RRU-100 — Full lucide catalog through @raulrod/icons",
  },
} as const;

type EntryName = keyof typeof ENTRIES;

const requested = process.env.RRU_BASELINE_ENTRY ?? "full";

if (!(requested in ENTRIES)) {
  throw new Error(
    `RRU_BASELINE_ENTRY="${requested}" no existe. Valores válidos: ${Object.keys(ENTRIES).join(", ")}.`,
  );
}

const entry = ENTRIES[requested as EntryName];

export default defineConfig(
  mergeConfig(baseConfig, {
    build: {
      outDir: entry.outDir,
      emptyOutDir: true,
      rollupOptions: {
        input: entry.input,
        // An app build keeps the entry's exports out of the bundle
        // (`preserveEntrySignatures: false`), and these entries are nothing but
        // an array of imports: Rollup would correctly conclude that nobody reads
        // them and shake the whole library away — a 0 kB bundle that "proves"
        // nothing. Keeping the signature makes every generated import reachable,
        // which is exactly what the measurement needs.
        preserveEntrySignatures: "strict",
      },
    },
    plugins: [
      visualizer({
        filename: `${entry.outDir}/stats.html`,
        gzipSize: true,
        brotliSize: false,
        open: false,
        title: entry.title,
      }),
      visualizer({
        filename: `${entry.outDir}/stats.json`,
        template: "raw-data",
        gzipSize: true,
        brotliSize: false,
        open: false,
      }),
    ],
  }),
);
